// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBE6a-srDZuBXYVSzbMTX5_rLZO7yKPwA',
    appId: '1:830323394728:android:b05abd5bc269b8e7b25a9d',
    messagingSenderId: '830323394728',
    projectId: 'real-notes-49ed5',
    databaseURL: 'https://real-notes-49ed5-default-rtdb.firebaseio.com',
    storageBucket: 'real-notes-49ed5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABEG_1Lif1roeJA4Fehl70PrfH0dUIthU',
    appId: '1:830323394728:ios:6024ff3ab82c1971b25a9d',
    messagingSenderId: '830323394728',
    projectId: 'real-notes-49ed5',
    databaseURL: 'https://real-notes-49ed5-default-rtdb.firebaseio.com',
    storageBucket: 'real-notes-49ed5.appspot.com',
    iosClientId:
        '830323394728-rh2ae6t524siccp58jignmlubmm9f58s.apps.googleusercontent.com',
    iosBundleId: 'com.example.realNotes',
  );
}
